// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
// SPDX-License-Identifier: BSD-3-Clause
const char apriltag_estimate_tag_pose_docstring[] =
"estimate_tag_pose(detection, tagsize, fx, fy, cx, cy) -> dict\n"
"\n"
"SYNOPSIS\n"
"\n"
"    import cv2\n"
"    import numpy as np\n"
"    from apriltag import apriltag\n"
"\n"
"    imagepath = '/tmp/tst.jpg'\n"
"    image     = cv2.imread(imagepath, cv2.IMREAD_GRAYSCALE)\n"
"    detector = apriltag(\"tag36h11\")\n"
"\n"
"    detections = detector.detect(image)\n"
"    if detections:\n"
"        # Estimate pose for the first detected tag\n"
"        # tagsize is the physical size of the tag in meters\n"
"        # fx, fy are focal lengths in pixels\n"
"        # cx, cy are principal point coordinates in pixels\n"
"        pose = detector.estimate_tag_pose(detections[0], \n"
"                                         tagsize=0.16,     # 16cm tag\n"
"                                         fx=600, fy=600, # focal lengths\n"
"                                         cx=320, cy=240) # principal point\n"
"        print(\"Rotation matrix R:\\n\", pose['R'])\n"
"        print(\"Translation vector t:\", pose['t'])\n"
"        print(\"Reprojection error:\", pose['error'])\n"
"\n"
"DESCRIPTION\n"
"\n"
"The estimate_tag_pose() method estimates the 6-DOF pose (position and orientation)\n"
"of a detected AprilTag in 3D space. This method requires the detection result from\n"
"the detect() method, the physical size of the tag, and camera intrinsic parameters.\n"
"\n"
"The pose estimation uses the homography matrix from the detection result to\n"
"compute the transformation from the tag's coordinate system to the camera's\n"
"coordinate system.\n"
"\n"
"ARGUMENTS\n"
"\n"
"- detection: A dictionary containing detection information returned by the\n"
"  detect() method. This dictionary must include the 'homography' key with the\n"
"  3x3 homography matrix.\n"
"\n"
"- tagsize: The physical side length of the AprilTag in meters. This is the real-\n"
"  world size of the tag, which is necessary for computing the scale of the pose.\n"
"\n"
"- fx: Focal length in the x direction in pixels. This is a camera intrinsic\n"
"  parameter that describes how the camera projects 3D points to 2D image space.\n"
"\n"
"- fy: Focal length in the y direction in pixels. This is a camera intrinsic\n"
"  parameter that describes how the camera projects 3D points to 2D image space.\n"
"\n"
"- cx: Principal point x coordinate in pixels. This is the x coordinate of the\n"
"  optical center of the camera in the image.\n"
"\n"
"- cy: Principal point y coordinate in pixels. This is the y coordinate of the\n"
"  optical center of the camera in the image.\n"
"\n"
"RETURNED VALUE\n"
"\n"
"Returns a dictionary containing:\n"
"\n"
"- 'R': 3x3 rotation matrix as a numpy array that represents the orientation\n"
"  of the tag in the camera coordinate system.\n"
"\n"
"- 't': 3x1 translation vector as a numpy array (in meters) that represents the\n"
"  position of the tag in the camera coordinate system.\n"
"\n"
"- 'error': The object-space error after the iteration process, representing \n"
"  the sum of squared reprojection errors between observed and  estimated points \n"
"  in object space. A lower value indicates a better pose estimate.\n"
"";
