ekf_filter_node:
  ros__parameters:
    frequency: 50
    imu0: /imu/data
    pose0: /landing_target_pose
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, true]
    pose0_config: [true, true, true,
                   true, true, true,
                   false, false, false,
                   false, false, false]
